typography_spectrum: 0.8400208661332726
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.5329667467158288
  lightness: 0.4815970615018159
  saturation: 0.08166239666752517
  rhythmicContrast: 0.2780385974328965
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.4502996599767357
analytics:
  google: null
  facebook: null
  twitter: null
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/44e43732-34fd-402f-9a18-138682ccf2bd.png
name: esportstest
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Esport
description: Wetten
purpose: []
